"""Update Last Modified Date to int

Revision ID: 0e8694e2dc46
Revises: 6752fec11f34
Create Date: 2024-11-09 09:41:23.528959

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "0e8694e2dc46"
down_revision = "6752fec11f34"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "parameter",
        "LastModifiedDate",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using='"LastModifiedDate"::integer',
    )
    op.drop_index("ix_parameter_name", table_name="parameter")
    op.create_index(op.f("ix_parameter_Name"), "parameter", ["Name"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_parameter_Name"), table_name="parameter")
    op.create_index("ix_parameter_name", "parameter", ["Name"], unique=True)
    op.alter_column(
        "parameter",
        "LastModifiedDate",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
