"""Add Parameter 2

Revision ID: 19f63edd7c24
Revises: 50785018df6b
Create Date: 2024-11-08 09:07:38.851824

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '19f63edd7c24'
down_revision = '50785018df6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
