"""Mimic aws value names

Revision ID: 6752fec11f34
Revises: 19f63edd7c24
Create Date: 2024-11-09 09:26:11.005682

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "6752fec11f34"
down_revision = "19f63edd7c24"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "parameter",
        sa.Column(
            "ARN",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default="",
        ),
    )
    op.alter_column("parameter", "name", nullable=False, new_column_name="Name")
    op.alter_column("parameter", "value", nullable=False, new_column_name="Value")
    op.alter_column("parameter", "type", nullable=False, new_column_name="Type")
    op.alter_column("parameter", "version", nullable=False, new_column_name="Version")
    op.alter_column(
        "parameter", "data_type", nullable=False, new_column_name="DataType"
    )
    op.alter_column(
        "parameter",
        "last_modified_date",
        nullable=False,
        new_column_name="LastModifiedDate",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("parameter", "Name", nullable=False, new_column_name="name")
    op.alter_column("parameter", "Value", nullable=False, new_column_name="value")
    op.alter_column("parameter", "Type", nullable=False, new_column_name="type")
    op.alter_column("parameter", "Version", nullable=False, new_column_name="version")
    op.alter_column(
        "parameter", "DataType", nullable=False, new_column_name="data_type"
    )
    op.alter_column(
        "parameter",
        "LastModifiedDate",
        nullable=False,
        new_column_name="last_modified_date",
    )
    op.drop_column("parameter", "ARN")
    # ### end Alembic commands ###
