"""empty message

Revision ID: a95e5a6bb8cc
Revises: 0e8694e2dc46
Create Date: 2025-05-13 14:24:35.868237

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "a95e5a6bb8cc"
down_revision = "0e8694e2dc46"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "parameter",
        "Name",
        type_=sqlmodel.sql.sqltypes.AutoString(length=None),
        nullable=False,
    )
    op.alter_column(
        "parameter",
        "Value",
        type_=sqlmodel.sql.sqltypes.AutoString(length=None),
        nullable=False,
    )
    op.alter_column(
        "parameter",
        "Type",
        type_=sqlmodel.sql.sqltypes.AutoString(length=None),
        nullable=False,
    )
    op.alter_column(
        "parameter",
        "DataType",
        type_=sqlmodel.sql.sqltypes.AutoString(length=None),
        nullable=False,
    )
    op.alter_column(
        "parameter",
        "LastModifiedDate",
        type_=sqlmodel.sql.sqltypes.AutoString(length=None),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "parameter",
        "LastModifiedDate",
        type_=sqlmodel.sql.sqltypes.AutoString(length=255),
        nullable=False,
    )
    op.alter_column(
        "parameter",
        "DataType",
        type_=sqlmodel.sql.sqltypes.AutoString(length=255),
        nullable=False,
    )
    op.alter_column(
        "parameter",
        "Type",
        type_=sqlmodel.sql.sqltypes.AutoString(length=255),
        nullable=False,
    )
    op.alter_column(
        "parameter",
        "Value",
        type_=sqlmodel.sql.sqltypes.AutoString(length=255),
        nullable=False,
    )
    op.alter_column(
        "parameter",
        "Name",
        type_=sqlmodel.sql.sqltypes.AutoString(length=255),
        nullable=False,
    )
    # ### end Alembic commands ###
